### ISSUE TITLE
Deprecated selector in `tomorrow-night-eighties/index.less`

### ISSUE THREAD

**Issue by icanswiftabit** [blakehall/tomorrow-night-eighties#7]
In `tomorrow-night-eighties/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.atom-text-editor,
.atom-text-editor .gutter,
:host,
:host .gutter` => `.atom-text-editor,
.atom-text-editor .gutter,atom-text-editor,atom-text-editor .gutter`

* `.atom-text-editor.is-focused .cursor,
:host(.is-focused) .cursor` => `.atom-text-editor.is-focused .cursor,atom-text-editor .cursor`

* `.atom-text-editor.is-focused .selection .region,
:host(.is-focused) .selection .region` => `.atom-text-editor.is-focused .selection .region,atom-text-editor .selection .region`

* `.atom-text-editor.is-focused .line-number.cursor-line-no-selection,
.atom-text-editor.is-focused .line.cursor-line,
:host(.is-focused) .line-number.cursor-line-no-selection,
:host(.is-focused) .line.cursor-line` => `.atom-text-editor.is-focused .line-number.cursor-line-no-selection,
.atom-text-editor.is-focused .line.cursor-line,atom-text-editor .line-number.cursor-line-no-selection,atom-text-editor .line.cursor-line`

* `.comment` => `.syntax--comment`

* `.keyword.operator.class,
.constant.other,
.source.php.embedded.line` => `.syntax--keyword.syntax--operator.syntax--class,
.syntax--constant.syntax--other,
.syntax--source.syntax--php.syntax--embedded.line`

* `.variable,
.support.other.variable,
.string.other.link,
.entity.name.tag,
.entity.other.attribute-name,
.meta.tag,
.declaration.tag` => `.syntax--variable,
.syntax--support.syntax--other.syntax--variable,
.syntax--string.syntax--other.syntax--link,
.syntax--entity.syntax--name.syntax--tag,
.syntax--entity.syntax--other.syntax--attribute-name,
.syntax--meta.syntax--tag,
.syntax--declaration.syntax--tag`

* `.constant.numeric,
.constant.language,
.support.constant,
.constant.character,
.variable.parameter,
.punctuation.section.embedded,
.keyword.other.unit` => `.syntax--constant.syntax--numeric,
.syntax--constant.syntax--language,
.syntax--support.syntax--constant,
.syntax--constant.syntax--character,
.syntax--variable.syntax--parameter,
.syntax--punctuation.syntax--section.syntax--embedded,
.syntax--keyword.syntax--other.syntax--unit`

* `.entity.name.class,
.entity.name.type.class,
.support.type,
.support.class` => `.syntax--entity.syntax--name.syntax--class,
.syntax--entity.syntax--name.syntax--type.syntax--class,
.syntax--support.syntax--type,
.syntax--support.syntax--class`

* `.string,
.constant.other.symbol,
.entity.other.inherited-class,
.markup.heading` => `.syntax--string,
.syntax--constant.syntax--other.syntax--symbol,
.syntax--entity.syntax--other.syntax--inherited-class,
.syntax--markup.syntax--heading`

* `.keyword.operator,
.constant.other.color` => `.syntax--keyword.syntax--operator,
.syntax--constant.syntax--other.syntax--color`

* `.entity.name.function,
.meta.function-call,
.support.function,
.keyword.other.special-method,
.meta.block-level` => `.syntax--entity.syntax--name.syntax--function,
.syntax--meta.syntax--function-call,
.syntax--support.syntax--function,
.syntax--keyword.syntax--other.syntax--special-method,
.syntax--meta.syntax--block-level`

* `.keyword,
.storage,
.storage.type,
.entity.name.tag.css` => `.syntax--keyword,
.syntax--storage,
.syntax--storage.syntax--type,
.syntax--entity.syntax--name.syntax--tag.syntax--css`

* `.invalid` => `.syntax--invalid`

* `.meta.separator` => `.syntax--meta.syntax--separator`

* `.invalid.deprecated` => `.syntax--invalid.syntax--deprecated`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by blakehall** [comment]
There isn't a single use of `:host` or `::shadow` in this project.

If I'm mistaken please submit a PR with the changes.

**Comment by hugomn** [comment]
I still seeing the same issue here. Is it a false deprecated message from Atom?

**Comment by blakehall** [comment]
@hugomn there isn't a single instance of either of the selectors mentioned in this issue in the `index.less` file for this theme.

If you are seeing other deprecation notices please open another issue.
